CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    FIRSTNAME VARCHAR(63),
    LASTNAME VARCHAR(63),
    ROLE VARCHAR(15) DEFAULT 'STUDENT'
);

CREATE INDEX idx_email ON users (EMAIL);

CREATE TABLE CHALLENGES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CREATOR_ID INT NOT NULL REFERENCES USERS(ID), 
    STATUS VARCHAR(15),
    TOTAL INT
);

CREATE INDEX idx_creator_idame ON challenges (CREATOR_ID);

CREATE TABLE RESULTS (
    CHALLENGE_ID INT NOT NULL REFERENCES CHALLENGES(ID),
    GRADE INT,
    USER_ID INT NOT NULL REFERENCES USERS(ID),
    STEPS_VALIDATED INT NOT NULL DEFAULT 0,
    DATABASE_CREDENTIALS JSON,
    PRIMARY KEY (CHALLENGE_ID, USER_ID)
);

CREATE INDEX idx_challenge_id ON RESULTS (CHALLENGE_ID);
CREATE INDEX idx_user_id ON RESULTS (USER_ID);

CREATE TABLE QUESTIONS (
    ID SERIAL PRIMARY KEY,
    CHALLENGE_ID INT NOT NULL REFERENCES CHALLENGES(ID),
    QUESTION TEXT NOT NULL,
    EXPECTED_ANSWER TEXT NOT NULL,
    COMMAND TEXT NOT NULL,
    VALUE INT
);

CREATE INDEX idx_challenge_id_question ON QUESTIONS (CHALLENGE_ID);
