version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ourGreatUser
      POSTGRES_PASSWORD: ourGreatPassword
      POSTGRES_DB: challenges
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db_data:
